server:
  port: 8080

github:
  client:
    id: fbba6328edb300654cc7
    secret: 89840cc55fde81aa90585a43fc38de30ef231574
  redirect:
    uri: http://localhost:8080/callback

#mybatis:
#  datasource:
#    url: jdbc:h2:~/community
#    username: sa
#    password: 123
#    driver-class-name: org.h2.Driver
