server:
  port: 8080
  servlet:
    session:
      timeout: 15552000

github:
  client:
    id: fbba6328edb300654cc7
    secret: 89840cc55fde81aa90585a43fc38de30ef231574
  redirect:
    uri: http://localhost:8080/callback


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.nky.community.mapper
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 10
      initial-size: 15
      max-active: 30
  thymeleaf:
    cache: false
#    url: jdbc:h2:~/community
#    username: sa
#    password: 123
#    driver-class-name: org.h2.Driver


logging:
  level:
    root: info
    com.nky.community.mapper: debug
    org.springframework.security: warn
  file: logs/community.log
  file.max-history: 15
  file.max-size: 100MB

